fastlane_require 'dotenv'

before_all do
  Dotenv.overload('.env')
end

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy a new version to Firebase App Distribution"
  lane :firebase_deploy do
  gradle(task: "clean assembleRelease")
  # Ensure APP_ID_FIREBASE is set in your environment variables
  if ENV["APP_ID_FIREBASE"].nil?
    UI.user_error!("APP_ID_FIREBASE environment variable is not set.")
  end
  # Ensure APP_ID_FIREBASE is set in your environment variables
  if ENV["FIREBASE_CLI_TOKEN"].nil?
    UI.user_error!("FIREBASE_CLI_TOKEN environment variable is not set.")
  end

  firebase_app_distribution(
    app: ENV["APP_ID_FIREBASE"],
    groups: "Testers", # Optional: distribute to groups
    release_notes: "Optional release notes", # Optional: add release notes
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"] # Optional: specify if not using default credentials
  )
  end
end