name: Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Adjust according to your project's Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Android SDK (only if Android)
        uses: actions/setup-android@v3
        with:
          java-version: '11'

      - name: Set up Fastlane
        run: bundle exec fastlane install_plugins

      - name: Run Fastlane for Android (if applicable)
        if: github.event_name == 'push'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: bundle exec fastlane android distribute_to_firebase
